# templates/prometheus-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prometheus.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.name }}
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}
          ports:
            - containerPort: {{ .Values.prometheus.port }}
          volumeMounts:
            - name: prometheus-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-volume
          configMap:
            name: prometheus-config